[font]
size = 10
normal.family = "Cascadia Code NF"
normal.style = "Regular"
offset.y = -2

[colors.primary]
background = "#000000"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
